title: Shaping Hearts
url: https://shapinghearts.sg
favicon: /images/favicon_32x32.png
colors:
  primary-color: "#c5242f"
  secondary-color: "#e00537"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Singapore's Largest Inclusive Arts Event
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d2acipkzjpm9pg.amplifyapp.com
prod: https://master.d2d4qnv3td402n.amplifyapp.com
facebook-pixel: ""
shareicon: /images/NECDC_Shaping_Hearts__Logo_Full_Colour_RGB_main_logo.jpg
is_government: false
google_analytics_ga4: G-64Y87LJS7H
linkedin-insights: ""
